sudo: false
dist: trusty
language: node_js
node_js:
  - '7'
  - '8'

addons:
  chrome: stable

before_script:
- npm install -g @angular/cli
- npm install

cache:
  directories:
    - ./node_modules/
script: npm test
