sudo: false
dist: trusty
language: node_js
node_js:
  - '7'
  - '8'

addons:
  chrome: stable

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install

cache:
  directories:
    - ./node_modules/
script: ng test --watch false
