sudo: false
dist: trusty
language: node_js
node_js:
  - '7'
  - '8'

addons:
  chrome: stable

#need this to trigger headlessness of chrome for travis build
before_install:
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install

cache:
  directories:
    - ./node_modules/

script:
  - ng lint
  - ng test --watch false
