sudo: false
dist: trusty
language: node_js
node_js:
  - '7'
  - '8'

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  chrome: stable

#this is required to make karma work on travis
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

install:
- npm install
- npm install d3

cache:
  directories:
    - ./node_modules/

script:
  - ng lint
  - ng test --watch false
